name: Build, Test & Nmap Scan

on:
  push:
    branches:
      - master

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for Juice Shop to be ready
        run: |
          for i in {1..10}; do
            if curl --silent http://localhost:3000; then
              echo "Juice Shop is up"
              break
            fi
            sleep 5
          done

      - name: Install nmap
        run: sudo apt-get update && sudo apt-get install -y nmap

      - name: Scan juice shop on host
        run: |
          mkdir -p scan-results
          nmap -Pn -sT -p 3000 127.0.0.1 -sV --script vuln -oA scan-results/juice-nmap

      - name: Upload nmap report artifact
        uses: actions/upload-artifact@v4
        with:
          name: nmap-report
          path: scan-results/*