name: SQLMap Scan

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  sqlmap_scan:
    runs-on: ubuntu-latest
    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000
    steps:
      - name: Wait for Juice Shop to be ready
        run: |
          for i in {1..15}; do
            if curl --silent http://localhost:3000; then
              echo "Juice Shop is up"
              break
            fi
            sleep 5
          done

      - name: Install sqlmap
        run: sudo apt-get update && sudo apt-get install -y sqlmap

      - name: Run sqlmap scan on login API
        run: |
          mkdir -p scan-results/sqlmap
          sqlmap -u "http://localhost:3000/rest/user/login" \
            --method POST \
            --data '{"email":"test@test.com","password":"test123"}' \
            --headers="Content-Type: application/json" \
            --batch --output-dir=scan-results/sqlmap --ignore-code=401 \
            --level=5 --risk=3 \
            --alert="echo '❌ SQL Injection vulnerability found! Failing the workflow.' && exit 1"

      - name: Upload sqlmap report artifact
        uses: actions/upload-artifact@v4
        with:
          name: sqlmap-login-report
          path: scan-results/sqlmap/*