name: ZAP Baseline Scan

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for Juice Shop to be ready
        run: |
          for i in {1..15}; do
            if curl --silent http://localhost:3000; then
              echo "Juice Shop is up"
              break
            fi
            sleep 5
          done

      - name: List files for debug
        run: ls -la

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:3000'
          fail_action: true
          cmd_options: '-c .zap-config.yaml'

      - name: Upload ZAP report artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html